crun:
	@g++ `find src/ -path '*.cpp'` -std=c++17 -o bin/sfmlgame -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
	@./bin/sfmlgame
run:
	./bin/sfmlgame
compile:
	g++ `find src/ -path '*.cpp'` -std=c++17 -o bin/sfmlgame -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
vrun:
	@g++ `find src/ -path '*.cpp'` -std=c++17 -o bin/vapp
	@./bin/vapp
