crun:
	@g++ src/*.cpp -I src -std=c++17 -o bin/sfmlgame -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
	@./bin/sfmlgame
run:
	./bin/sfmlgame
compile:
	g++ src/*.cpp -I src -std=c++17 -o bin/sfmlgame -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
